### ISSUE TITLE
QSG-ArrayCapacity.pdf is a copy of QSG-ArrayProduct.pdf

### ISSUE THREAD

**Issue by ddeel** [FarmerMike252/SMI-S_Mocks#2]
In the QuickStartGuides directory, the "QSG-ArrayCapacity.pdf" file appears to be a copy of the "QSG-ArrayProduct.pdf" file, which does not talk about how to get Capacity information from an SMI-S implementation.

**Comment by FarmerMike252** [comment]
I fixed this and did the upload and verified that "QSG-ArrayCapacity.pdf" is the actual guide for Array Capacity (and no longer Array Product).
